#!/home/jdh4/.conda/envs/tree-env/bin/python

"""Leading spaces in each line of the output of sshare are used to determine
   the level of the tree.

   Note that andlinger has users at level 5 in the tree.

   from sharetree import ShareTree
   mytree = ShareTree(); mytree.get_raw_data(); mytree.parse()
"""


import os
import sys
import argparse
import textwrap
import config as c
from sharetree import ShareTree
from sharetree import ShareTreeError
from single_job import SingleJobBreakdown
from sprio_weights import SprioWeights
try:
    from blessed import Terminal
    blessed_is_available = True
except ModuleNotFoundError:
    blessed_is_available = False


WIDTH = 80


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="myshare - Shares of a user")
    parser.add_argument("-u", "--user", type=str, default=os.environ["USER"], help="NetID of the user")
    parser.add_argument("-v", "--verbose", action="store_true", help="Show more details")
    parser.add_argument("-d", "--debug", action="store_true", help="Print debug info")
    parser.add_argument("-A", "--account", type=str, default=None, help="Show usage by user for an account")
    args = parser.parse_args()

    term = Terminal()
    mytree = ShareTree()
    mytree.get_raw_data()
    try:
        mytree.parse(args.user)
    except ShareTreeError as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    if args.debug:
        print(mytree.analyze())
    if mytree.num_accounts == 0:
        print(f"{args.user} not found in the sshare tree.")

    print("─" * WIDTH)
    print("Why aren't my jobs running?".center(WIDTH))
    print("─" * WIDTH)


    ###################
    ## A C C O U N T ##
    ###################
    if args.account:
        node_id = f"{args.account} (--)"
        if node_id in mytree.tree:
            mytree.draw_subtree(node_id, args.account)
            fields = ("User", "Account", "Usage", "LevelFS", "Fairshare")
            # TODO: add args.user to get_descendants_table so that line can be bolded/colored, maybe same for dept
            table = mytree.get_descendants_table(node_id, decimals=1, sort_by="Usage", tabbing=-2, fields=fields)
            num_table_lines = len(table.splitlines())
            if "No table since" not in table and num_table_lines > 2:
                print(f'\nAll users under account "{args.account}" are shown below sorted by Usage:\n')
                print(table)
                print('Note: Users with zero "Usage" are not shown.')
            elif num_table_lines == 2:
                print(f'\nAll users under account "{args.account}" are shown below sorted by Usage:\n')
                print(table, end="")
                print("    No users shown since all users have zero Usage")
            else:
                print(table)
        else:
            msg = f'The Slurm account "{args.account}" was not found in the sshare tree.'
            if "total (--)" in mytree.tree:
                children_of_total = [child.data.account
                                     for child in mytree.tree.children("total (--)")]
                if children_of_total:
                    msg += " Below is a list of some of the valid accounts:"
                    print(textwrap.fill(msg, width=WIDTH), end="\n\n")
                    indent = " " * 4
                    accounts = textwrap.fill((", ").join(children_of_total),
                                             width=WIDTH,
                                             initial_indent=indent,
                                             subsequent_indent=indent)
                    print(accounts)
                    print("\nFor example:")
                    print(f"\n{indent}$ stree -a {children_of_total[0]}")
            else:
                print(msg)
            sys.exit(1)
        sys.exit(0)


    #############
    ## U S E R ##
    #############
    for node_id in mytree.tree.expand_tree():
        if node_id.endswith(f" ({args.user})"):
            mytree.draw_subtree(node_id, args.user)
            fs = float(mytree.tree[node_id].data.fair_share)
            print(mytree.format_fairshare(fs))
            print("")
            print(mytree.explain(fs))
            print(f"Department shares: {mytree.get_dept(node_id)}\n")
            print("")
            print(mytree.get_descendants_table(node_id="total (--)", decimals=1, sort_by="RawShares", tabbing=-1))
            if args.verbose:
                path = list(mytree.tree.rsearch(node_id))
                path.reverse()
                for i, node_id in enumerate(path):
                    if node_id == "root (--)" or mytree.tree[node_id].is_leaf():
                        continue
                    level2 = f"{node_id.split()[0]}"
                    print(level2)
                    user_dept = path[2].split()[0] if node_id == "total (--)" else ""
                    print(mytree.get_descendants_table(node_id=node_id, decimals=1, tabbing=i-1, user_dept=user_dept), end="")
                    if not mytree.tree.children(node_id)[0].is_leaf():
                        print(f"{' ' * 5 * (i - 1)}|")
                        print(f"{' ' * 5 * (i - 1)} ────", end="")
                print("\n")
                s = ("Accounts with LevelFS > 1 have been under-served by Slurm. User within "
                     "those accounts will receive a priority boost. Similarly, accounts with "
                     "LevelFS < 1 will receive a priority penalty since they have been over-served. "
                     "When all accounts are running the shares breakdown will "
                     "reflect where the resources are allocated. The shares column "
                     "reflects the limiting distribution or what to expect over long times. "
                     "The good news for users in a department with 1 share or a small number of "
                     "shares is that the contributing departments often run fewer jobs "
                     "for periods of time. Then the effective shares increases for everyone else.\n")
                print(textwrap.fill(s, width=WIDTH))
                print("More important than shares is your LevelFS Rank at level 2\n")
                j = SingleJobBreakdown(args.user, fs)
                j.get_job_data()
                j.parse()
                if j.job_dict:
                    print(j.job_dict)
                    j.explain()
                sprio_tracker = SprioWeights()
                sprio_tracker.fetch_live()
                print(sprio_tracker.weights)

            if mytree.num_accounts > 1:
                print("\n\n==============================================================================\n\n")

    print("\n")
    print("-" * 80)
    print("For more details about your cluster share, run the following command:")
    print("    $ stree --verbose")
    print("\nFor more information about job priority, making a financial contribution\nto the cluster, additional GPUs at Princeton:")
    print(f"    {c.MORE_INFO_URL}")
